linux-balena-bootloader: Size reduction
Newer meta-balena updates are failing for iot-gate-imx8plus-sb with the error:
ERROR: balena-image-flasher-1.0-r0 do_resin_boot_dirgen_and_deploy: resin-boot: Not enough space for atomic copy operations.

Changelog-entry: Reduce the size of the balena bootloader by removing unused functionality
Signed-off-by: Florin Sarbu <florin@balena.io>